function [fitresult, gof] = createFits(x, y, x19, y19)
%CREATEFITS(X,Y,X19,Y19)
%  Create fits.
%
%  Data for 'Ex20' fit:
%      X Input : x
%      Y Output: y
%  Data for 'Ex19' fit:
%      X Input : x19
%      Y Output: y19
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-May-2014 15:58:26

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 2, 1 );
gof = struct( 'sse', cell( 2, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'Ex20'.
[xData, yData] = prepareCurveData( x, y );

% Set up fittype and options.
ft = fittype( 'a+b*x^2', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.239952525664903 0.41726706908437];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Ex20' );
h = plot( fitresult{1}, xData, yData );
legend( h, 'y vs. x', 'Ex20', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x' );
ylabel( 'y' );
grid on

%% Fit: 'Ex19'.
[xData, yData] = prepareCurveData( x19, y19 );

% Set up fittype and options.
ft = fittype( 'a*exp(b*x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.111202755293787 0.780252068321138];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Ex19' );
h = plot( fitresult{2}, xData, yData );
legend( h, 'y19 vs. x19', 'Ex19', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x19' );
ylabel( 'y19' );
grid on


