function [fitresult, gof] = createFit(x22, y22)
%CREATEFIT(X22,Y22)
%  Create a fit.
%
%  Data for 'Ex22' fit:
%      X Input : x22
%      Y Output: y22
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-May-2014 15:51:32


%% Fit: 'Ex22'.
[xData, yData] = prepareCurveData( x22, y22 );

% Set up fittype and options.
ft = fittype( 'a+b*log(x)', 'independent', 'x', 'dependent', 'y' );
opts = fitoptions( ft );
opts.Display = 'Off';
opts.Lower = [-Inf -Inf];
opts.StartPoint = [0.469390641058206 0.0119020695012414];
opts.Upper = [Inf Inf];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'Ex22' );
h = plot( fitresult, xData, yData );
legend( h, 'y22 vs. x22', 'Ex22', 'Location', 'NorthEast' );
% Label axes
xlabel( 'x22' );
ylabel( 'y22' );
grid on


